[build]
  command = """
    sed 's|{{ VITE_YOUTUBE_API_KEY }}|'\"$VITE_YOUTUBE_API_KEY\"'|g' env.js > env.prod.js
    cp config.prod.js config.js
  """
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"